### ISSUE TITLE
Docker下autocx.py无法正常运行

### ISSUE THREAD

**Issue by inewhero** [Luoofan/autochaoxing#12]
系统信息：Linux version 4.19.0-5-amd64 (debian-kernel@lists.debian.org) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP Debian 4.19.37-5+deb10u2 (2019-08-08)
按@KimJungWha 在[dockerhub页面](https://hub.docker.com/r/kimjungwha/autocx)的方法成功安装了autocx；
已正确配置了 logindata_phone.txt 和 logindata.txt，首次运行报错如下：
![bugreport1](https://user-images.githubusercontent.com/35384927/90341860-ea7a6600-e035-11ea-928a-5e869ef52e54.PNG)

**Comment by Luoofan** [comment]
我无法复现该错误，请问是否修改过源代码
另外，可以尝试将`src`文件夹下的`startdriver.py`文件中的第63、64行移至55、56行
即将
```py
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
```
移至`chrome_options.add_argument("--headless")`前面

**Comment by inewhero** [comment]
没有修改过源码。尝试将第63、64行移至55、56行后，报错信息不变。

**Comment by KimJungWha** [comment]
> 没有修改过源码。尝试将第63、64行移至55、56行后，报错信息不变。



我看您提供的截图上是在登陆报错是吗？很抱歉，我也无法复现该错误，我这里一切正常。步骤如图：  
![2020-08-17_16-14](https://user-images.githubusercontent.com/61445867/90374315-dec68800-e0a5-11ea-9c9f-0fa15ef93e35.png)

请问您的镜像是哪个版本如：win、arm，您的宿主机是 debian吗？您以前有没有旧版的镜像留存，程序运行因为各方面的因素影响，可能会有各种玄学问题的出现，请您确定安装的docke版本是`docker-ce`，删除所有autocx镜像，重新拉去镜像尝试，如果还有问题，欢迎加群联系我们

**Comment by Luoofan** [comment]
企鹅群号：1075080181
