### ISSUE TITLE
autocx.py 

### ISSUE THREAD

**Issue by KitsuneJoker** [Luoofan/autochaoxing#14]
我的autocx.py 无法打开
![M6@H$F)AQHY)KFHX_0~_O2E](https://user-images.githubusercontent.com/72750365/95760698-ebe6a880-0cdd-11eb-9b09-87cb192775d0.png)
超星自动>输入后没有后续，没有弹出窗口

**Comment by Luoofan** [comment]
看一下工作目录和python环境，chrome和相应驱动是否ok，账号密码是否填写

**Comment by KitsuneJoker** [comment]
请问工作目录应该在哪里，chrome我重下了最新版本，chromedriver我也下载了对应版本放着里面了。密码账号都填写了并且删除了提示词
![QQ图片20201013121123](https://user-images.githubusercontent.com/72750365/95814550-3bb08880-0d4d-11eb-9d67-88c5d36f10ae.png)

**Comment by Luoofan** [comment]
工作目录即`autocx.py`所在的目录

**Comment by KitsuneJoker** [comment]
是在autocx.py的目录下

**Comment by Luoofan** [comment]
方便的话，看一下工作目录的文件管理器截图

**Comment by KitsuneJoker** [comment]
我直接把文件夹放在桌面了
![QQ图片20201013172828](https://user-images.githubusercontent.com/72750365/95842810-93fd7f80-0d79-11eb-80c1-48f585baa099.png)

**Comment by Luoofan** [comment]
下载todesk远程一下吧

**Comment by KitsuneJoker** [comment]
我下好了

**Comment by Luoofan** [comment]
发送id和临时密码到`luooofan@qq.com`

**Comment by Luoofan** [comment]
SUMMARY：
- 配置好python环境，通过`python -V`查看
- 尽量从github下载项目，第三方提供的包可能未更新到最新
- 仔细看项目主页Readme以及doc目录下的FAQ
