### ISSUE TITLE
login failed,  please check your login_info

### ISSUE THREAD

**Issue by Zy143L** [Luoofan/autochaoxing#15]
![image](https://user-images.githubusercontent.com/21352718/99571425-40342500-2a0e-11eb-8f28-ded6576c236c.png)
密码中含有@ 莫非是这个问题?
腾讯云服务器
Centos7.4系统 Docker模式

**Comment by Zy143L** [comment]
使用学校模式  get school_id failed

**Comment by Luoofan** [comment]
超星屏蔽了腾讯云，故脚本无法访问超星网站，无法登录

**Comment by Zy143L** [comment]
> 超星屏蔽了腾讯云，故脚本无法访问超星网站，无法登录

多谢
