### ISSUE TITLE
SSL错误

### ISSUE THREAD

**Issue by nekobest** [Luoofan/autochaoxing#16]
`ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1122)`

已安装依赖

**Comment by Luoofan** [comment]
无法复现错误，需要更多信息。

**Comment by nekobest** [comment]
SSL错误确定了是Windows网络的问题，现在换用Linux，系统版本是Ubuntu20.04,arm64
报错：
Traceback (most recent call last):
  File "autocx.py", line 26, in <module>
    from docker import StartAutoCX
ImportError: cannot import name 'StartAutoCX' from 'docker' (/usr/lib/python3/dist-packages/docker/__init__.py)

**Comment by nekobest** [comment]
解决了，原来是因为本地安装了docker这个依赖... 把docker改成别的名儿就成了
