### ISSUE TITLE
自动答题只能答单选题，多选题只能选一个选一项

### ISSUE THREAD

**Issue by 19819068211** [Luoofan/autochaoxing#17]
这个程序自动答题，自动答题只能答单选题，多选题只能选一个选项

**Comment by Luoofan** [comment]
自动答题依赖于现成的接口，不稳定。
根据已有的信息无法确定是脚本执行逻辑的问题还是查题接口的问题。

对分数有要求的话，可以配置`-n`选项，控制答题策略；也可以不答题。
参考[FAQ-关于查题](https://github.com/Luoofan/autochaoxing/blob/master/doc/FAQ.md#about-query-questions-%E5%85%B3%E4%BA%8E%E6%9F%A5%E9%A2%98)
