### ISSUE TITLE
无法正常获取未完成章节

### ISSUE THREAD

**Issue by nekobest** [Luoofan/autochaoxing#19]
可以成功登录、获取课程，但获取到的未完成章节数为0，导致无法刷课

**Comment by Luoofan** [comment]
是普通章节吗

**Comment by nekobest** [comment]
是的，之前可以正常刷的，应该与课程无关。
有什么可以debug的方法吗？

**Comment by Luoofan** [comment]
课程目录网页部分标签有所更改导致获取不到未完成章节，已提交修复
更新后看是否解决
