### ISSUE TITLE
cannot create temp dir for user data dir

### ISSUE THREAD

**Issue by 19819068211** [Luoofan/autochaoxing#20]
![Screenshot_20210408_150608_com microsofts rdc android](https://user-images.githubusercontent.com/66981884/113983039-0f993e80-987c-11eb-8f00-06eedd10a641.jpg)
cannot create temp dir for user data dir

**Comment by Luoofan** [comment]
Try these solutions.
[cannot-create-temp-dir-for-user-data-dir-error-when-not-running-as-admin](https://stackoverflow.com/questions/46066670/cannot-create-temp-dir-for-user-data-dir-error-when-not-running-as-admin)
[unknown-error-cannot-create-temp-dir-for-user-data-dir-in-chrome-driver](https://stackoverflow.com/questions/47259763/unknown-error-cannot-create-temp-dir-for-user-data-dir-in-chrome-driver)

Maybe you should focus on the TEMP or TMP environment variables.

**Comment by 19819068211** [comment]
已解决，谢谢
