### ISSUE TITLE
关于docker版本运行

### ISSUE THREAD

**Issue by 19819068211** [Luoofan/autochaoxing#22]
![Screenshot_20210416_114731_com sonelli juicessh](https://user-images.githubusercontent.com/66981884/114969078-396ce980-9eaa-11eb-8180-074769ceb6ac.jpg)
请问运行docker版本后如图该怎么办

**Comment by KimJungWha** [comment]
> ![Screenshot_20210416_114731_com Sonelli juicessh](https://user-images.githubusercontent.com/66981884/114969078-396ce980-9eaa-11eb-8180-074769ceb6ac.jpg)
> 请问运行docker版本后如图该怎么办

脚本已经更新，新的 Docker 镜像也推送到了 Docker Hub，可以重新更新镜像再试

**Comment by 19819068211** [comment]
![Screenshot_20210422_115701_com sonelli juicessh](https://user-images.githubusercontent.com/66981884/115653708-379b9e00-a362-11eb-9cf3-c836cf220039.jpg)
作者大大，还是不太行
