### ISSUE TITLE
想请问下这个是运行完成了吗？

### ISSUE THREAD

**Issue by 741243716** [Luoofan/autochaoxing#3]
想请问下这个是运行完成了吗？我运行了之后在web登陆上去没什么变化呀！
![112](https://user-images.githubusercontent.com/36138300/80190447-e79ed400-8646-11ea-9a2c-c6b4ad2595c2.png)

**Comment by Luoofan** [comment]
是否有弹出其他窗口，如果没有弹出的话请检验你的账户格式是否输入正确，如果有的话请附图

**Comment by 741243716** [comment]
> 是否有弹出其他窗口，如果没有弹出的话请检验你的账户格式是否输入正确，如果有的话请附图

没有弹出其他窗口，就先弹出上面两个窗口然后最后这个窗口就到按任意键继续，按键了就让退出程序了，我确定我账号密码是正确的。

**Comment by 741243716** [comment]
> 是否有弹出其他窗口，如果没有弹出的话请检验你的账户格式是否输入正确，如果有的话请附图

而且弹出来的两个窗口分别是手机登录和机构登录的，登录了之后就没任何弹窗了

**Comment by Luoofan** [comment]
弹出的窗口中没有输出任何信息吗

**Comment by 741243716** [comment]
> 弹出的窗口中没有输出任何信息吗

没有

**Comment by 741243716** [comment]
> 弹出的窗口中没有输出任何信息吗

是不是chromedriver的问题？chromedriver是不是下载后要重命名为chromedriver？

**Comment by 741243716** [comment]
> 弹出的窗口中没有输出任何信息吗

![12314141](https://user-images.githubusercontent.com/36138300/80192684-27b38600-864a-11ea-8d8b-32717a4f90eb.png)

**Comment by Luoofan** [comment]
嗯，需要重命名为chromedriver

**Comment by 741243716** [comment]
> 嗯，需要重命名为chromedriver

我重命名之后再测试还是一样的结果噢

**Comment by Luoofan** [comment]
请检查登录信息是否分行填写，如果是，请加qq群1075080181来交流
