### ISSUE TITLE
大佬有没有可能自定义搜题api

### ISSUE THREAD

**Issue by yuzhenglong1** [Luoofan/autochaoxing#4]
不知道怎么改，给点提示吧

**Comment by Luoofan** [comment]
自定义搜题api需要自行添加或修改代码；(*由于查题接口的差异性无法提供统一的简单的添加方式*)
脚本目前支持自定义搜题api**优先级**，我已经在FAQ里补充；
当然，如果你有其他的好用的查题api并且愿意分享的话，可以share然后我来补充🤝

**Comment by Luoofan** [comment]
如果没有后续问题的话我将关闭该issue
