### ISSUE TITLE
不能运行 错误如下

### ISSUE THREAD

**Issue by rk2592000936** [Luoofan/autochaoxing#5]
![image](https://user-images.githubusercontent.com/50093450/82423576-84be2280-9ab6-11ea-8f03-a28359c7efe8.png)
应该如何解决？？

**Comment by Luoofan** [comment]
### **请描述清楚问题**
根据经验来看我想应该已经成功运行exe了（效果是命令行的启动）
出现该问题应该是：使用机构账户登录的前提下会弹出验证码，但你的计算机因为某些原因不能自动打开验证码图片，这种情况下你只需要**手动打开目录下的验证码图片**并**在命令行填写**即可。
当然，也有可能是你未删掉logindata.txt中的提示信息导致冗余命令行的出现。
