### ISSUE TITLE
一直卡在章节测验

### ISSUE THREAD

**Issue by rk2592000936** [Luoofan/autochaoxing#6]
![image](https://user-images.githubusercontent.com/50093450/82432746-13d13780-9ac3-11ea-9411-0de989fd0fea.png)

如何解决

**Comment by Luoofan** [comment]
1. 尝试按回车键
2. 如果仍然不行，请重启脚本
3. 建议更换issue图片，或者把图片截短一些

**Comment by rk2592000936** [comment]
@Luoofan 回车键可以解决问题 但是不可能每次都要按一下回车吧 该问题的原因是什么

**Comment by Luoofan** [comment]
并非是脚本代码自身的问题，脚本会按序执行，没遇到问题的话顺利执行，反之会报错。在答题环节不会出现停止运行的情况。
至于该问题的原因，目前已知：过多地切换窗口会导致出现，一个比较明显的标志是当命令行窗口左上角出现“选择”二字的时候可能会出现该情况

**Comment by rk2592000936** [comment]
还有第二个需求 就是能不能从课程的某个章节开始刷 不需要从头开始 已开issue

**Comment by Luoofan** [comment]
嗯正在回复中，如果该issue已解决，请关闭，谢谢配合
