### ISSUE TITLE
能否选择从某个课程的某个章节开始刷 

### ISSUE THREAD

**Issue by rk2592000936** [Luoofan/autochaoxing#7]
不需要刷完整个课程

**Comment by Luoofan** [comment]
1. 脚本目前已支持**控制模式**，也即**从第一个未完成的任务点开始，完成到你选中的章节停止**。
要想启用控制模式，只需在执行脚本的时候指定-m control(或者--mode control)即可。
具体信息请见[FAQ](https://github.com/Luoofan/autochaoxing/blob/master/doc/FAQ.md)。
2. 脚本其实也支持从指定章节开始进行，但因为之前没有这样的需求，所以只供我自己用于debug使用。使用该模式只需在执行脚本的时候指定-m debug(或者--mode debug)即可（完成任务点：从选定章节到最后），你可以先使用一下看是否符合需求。

**Comment by Luoofan** [comment]
debug模式选择开始章节的时候注意要输入已列出标题中的连续部分。
eg：2-3-1|-| xxxxxxx
当脚本提示选择的时候，要想选择此章节可以输入2-3-1，或者2-3-1|-，等等
要求是**已列出标题中的连续部分**
